language: java
sudo: false
before_script:
- pip install --user codecov
install: true
script:
- mvn test -B -V
jdk:
- oraclejdk8
- openjdk7
after_success:
- codecov
notifications:
  slack: saucelabs:UuMma1Or531Mia6gJpFzwn5Z
env:
  global:
  - SAUCE_USERNAME=sauce_examples
  - secure: hSCw1EB+bAwdEY7KrE25WmKFlId7LyLOd2BWhiMmmwHI5+hkTdncWi9zmRfmVL4+4xX5M3IBhG6Bdie+5/r6okrp0yTJOxMrFetkGMNwNhBUxnQeH2k1xvUaZPL5coA8IdcDgszoOJEJCLUPbLEKM4reKX2mRBrDa1mVuD7oblE=
